# Generated by Django 4.2.4 on 2023-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name=40)),
                ("date", models.DateField()),
                ("text", models.CharField(verbose_name=256)),
                ("image", models.ImageField(upload_to="blog_images/")),
            ],
        ),
    ]
