# Generated by Django 4.2.4 on 2023-09-07 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="text",
            new_name="post_text",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="title",
            new_name="post_title",
        ),
    ]
