# Generated by Django 4.2.4 on 2023-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_text_posts_post_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="post_text",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="posts",
            name="post_title",
            field=models.CharField(max_length=40),
        ),
    ]
